# Generated by Django 3.0.7 on 2021-02-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
