# Generated by Django 3.0.7 on 2021-05-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
