# Generated by Django 3.0.7 on 2021-05-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_post_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
